###
# https://travis-ci.org/mcarey-solstice/cicd-helpers
##

language: general

sudo: true

services:
  - docker

env:
  global:
    - USE_DOCKER=true

before_install:
  - echo "Pulling docker images"
  - docker pull matejak/argbash
  - docker pull bats/bats
  - docker pull mcareysolstice/rst2man

before_script:
  - make scripts

script:
  - make test

before_deploy:
  - make VERSION=${TRAVIS_TAG} docs
  ###
  # Travis keeps the root permissions on new files
  - sudo chown -R travis:travis out
  ##
  - ./bin/package ${TRAVIS_TAG} dist

deploy:
- provider: script
  script: ./bin/distribute ${TRAVIS_TAG}
  skip_cleanup: true
  on:
    tags: true
- provider: releases
  api_key: $GITHUB_TOKEN
  file: dist/cicd-helpers-${TRAVIS_TAG}.tgz
  skip_cleanup: true
  on:
    tags: true
