#!/bin/bash

# Put this file to /etc/bash_completion.d/version_completion.sh_ENDL_()# needed because of Argbash --> m4_ignore([
### START OF CODE GENERATED BY Argbash v2.8.0 one line above ###
# Argbash is a bash code generator used to get arguments parsing right.
# Argbash is FREE SOFTWARE, see https://argbash.io for more info

_version_completion_sh ()
{
	local cur prev opts base
	COMPREPLY=()
	cur="${COMP_WORDS[COMP_CWORD]}"
	prev="${COMP_WORDS[COMP_CWORD-1]}"
	all_long_opts="--major --minor --patch --rc --help "
	all_short_opts="-h "
	case "$prev" in
		)
			COMPREPLY=( $(compgen -o bashdefault -o default -- "${cur}") )
			return 0
			;;
		*)
			case "$cur" in
				--*)
					COMPREPLY=( $(compgen -W "${all_long_opts}" -- "${cur}") )
					return 0
					;;
				-*)
					COMPREPLY=( $(compgen -W "${all_short_opts}" -- "${cur}") )
					return 0
					;;
				*)
					COMPREPLY=( $(compgen -o bashdefault -o default -- "${cur}") )
					return 0
					;;
			esac
	esac

}
complete -F _version_completion_sh version_completion.sh
### END OF CODE GENERATED BY Argbash (sortof) ### ])
